MATMULT_PRECISION = "medium"
MAX_DURATION = "01:00:00:00"

NUM_CLASSES = 5
LEARNING_RATE = 10e-3
MIN_EPOCHS = 0
MAX_EPOCHS = 10

DATA_DIR = "./data/aptos"
BATCH_SIZE = 32
NUM_WORKERS = 8
PIN_MEMORY = True

ACCELERATOR = "gpu"
DEVICES = [0]
PRECISION = "16-mixed"
